"use client"

import { useState, useEffect } from "react"
import { CryptoChartDashboard } from "@/components/crypto-chart-dashboard"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { RecentSignals } from "@/components/recent-signals"
import { NewsWidget } from "@/components/news-widget"
import { DataCollectionStatus } from "@/components/data-collection-status"
import { DataCollectionDialog } from "@/components/data-collection-dialog"
import { Watchlist } from "@/components/watchlist"
import { VirtualTradingHistory } from "@/components/virtual-trading-history"

export function DashboardPage() {
  const [activeTab, setActiveTab] = useState("chart")
  const [dataDialogOpen, setDataDialogOpen] = useState(false)

  // Listen for data collection events
  useEffect(() => {
    const handleDataCollected = () => {
      console.log("Data collection event detected in dashboard")
    }

    window.addEventListener("dataCollected", handleDataCollected)

    return () => {
      window.removeEventListener("dataCollected", handleDataCollected)
    }
  }, [])

  // Listen for data collection dialog open event
  useEffect(() => {
    const handleOpenDialog = () => {
      setDataDialogOpen(true)
    }

    window.addEventListener("openDataCollectionDialog", handleOpenDialog)

    return () => {
      window.removeEventListener("openDataCollectionDialog", handleOpenDialog)
    }
  }, [])

  return (
    <div className="grid gap-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">Crypto Trading Dashboard</h1>
        <DataCollectionDialog open={dataDialogOpen} onOpenChange={setDataDialogOpen} />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Main content - takes up 3/4 of the space */}
        <div className="lg:col-span-3">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
            <TabsList>
              <TabsTrigger value="chart">Chart Analysis</TabsTrigger>
              <TabsTrigger value="signals">Trading Signals</TabsTrigger>
              <TabsTrigger value="trading">Virtual Trading</TabsTrigger>
              <TabsTrigger value="news">News & Sentiment</TabsTrigger>
              <TabsTrigger value="data">Data Collection</TabsTrigger>
            </TabsList>
            <TabsContent value="chart" className="space-y-4">
              <CryptoChartDashboard />
            </TabsContent>
            <TabsContent value="signals" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Recent Trading Signals</CardTitle>
                  <CardDescription>Latest trading signals generated by the system</CardDescription>
                </CardHeader>
                <CardContent>
                  <RecentSignals />
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="trading" className="space-y-4">
              <VirtualTradingHistory />
            </TabsContent>
            <TabsContent value="news" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Crypto News & Sentiment</CardTitle>
                  <CardDescription>Latest news and sentiment analysis for cryptocurrencies</CardDescription>
                </CardHeader>
                <CardContent>
                  <NewsWidget />
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="data" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Data Collection History</CardTitle>
                  <CardDescription>View history of data collection activities</CardDescription>
                </CardHeader>
                <CardContent>
                  <DataCollectionStatus />
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>

        {/* Watchlist - takes up 1/4 of the space */}
        <div>
          <Watchlist />
        </div>
      </div>
    </div>
  )
}
